### ISSUE TITLE
Error `ndarray: index out of bounds`

### ISSUE THREAD

**Issue by abearab** [noamteyssier/sgcount#49]
I'm trying this code 
```bash
sgcount -l reference.fa -i Sample1_R1.trim.fastq.gz
```
and I get this error
```
 ⠉ [00:00:00] Calculating Offset
thread 'main' panicked at 'ndarray: index out of bounds', /data_gilbert/home/aarab/.cargo/registry/src/github.com-1ecc6299db9ec823/ndarray-0.15.6/src/arraytraits.rs:27:5
```
@noamteyssier, do you have any thoughts? 
___
```bash
cat reference.fa | head 
```
```
>oligo_1
GCGTCGTCGCGCAGAGCTGACTC
>oligo_2
GATTCGGACTCCATGCGGCGCAA
>oligo_3
CGCGTCGTCGCGCAGAGCTGACT
>oligo_4
TGCTGGGGAGTCGCCTACGCCTA
>oligo_5
GGACTCCATGCGGCGCAAGCGGC
```

```bash
zcat Sample1_R1.trim.fastq.gz | head
```
```
@A00351:765:HJMGMDRX2:2:2101:1615:1031 1:N:0:AACCGCGG+CTAGCGCT
ACCTTGGTTATTGGTCACTCTGT
+
:FFFFFF:FFFFFFFFFFFFFFF
@A00351:765:HJMGMDRX2:2:2101:1759:1031 1:N:0:AACCGCGG+CTAGCGCT
CCAAAGCCCGATACCTGAAGAAA
+
FFFFFFFFFFFFFFFFFFFFFFF
@A00351:765:HJMGMDRX2:2:2101:2302:1031 1:N:0:AACCGCGG+CTAGCGCT
GTCTTCCTCTTGAGTTATGCAGA
```

**Comment by noamteyssier** [comment]
Hey Abe,

Yeah it looks like the problem is the sequences are shorter than the library. I built this with the expectation that the input fastqs were untrimmed. I'll add a nicer error message for this.

Try running it on the untrimmed fastqs instead

**Comment by abearab** [comment]
Hi Noam, Thanks for your time. Yeah, when I'm trying it with non trimmed file it works. 

In general, the motivation for using your package started from this `bowtie2` job info:
```
920163 reads; of these:
  920163 (100.00%) were unpaired; of these:
    7179 (0.78%) aligned 0 times
    248203 (26.97%) aligned exactly 1 time
    664781 (72.25%) aligned >1 times
99.22% overall alignment rate
```
The `(72.25%) aligned >1 times` part doesn't make sense experimentally and it seems to be an issue with the `bowtie2` command I borrowed from [goodarzilab/iAnalyzer](https://github.com/goodarzilab/iAnalyzer). 

To my understanding, your package doesn't need trimming. But is there any way to now if there is reads aligned >1 times using `sgcount`?

**Comment by noamteyssier** [comment]
So this will never report multimatches because it's not an aligner. It's only looking for exact (or one off) pattern matches in the library and assuming a fixed length constant region (plus or minus one base pair). 

As a result you can never have multimatches, and since all library elements are guaranteed unique (or the program won't run) there are no ambiguous matches generated.

But I could add some summary statistics to show how many reads mapped and other things like that.

**Comment by noamteyssier** [comment]
tracking with #51
